export const smorfia = {
    1: "L’Italia - L’Italia",
    2: "‘A Piccerella – La bambina",
    3: "‘A Jatta – La gatta",
    4: "‘O puorco – Il maiale",
    5: "‘A Mano – La mano",
    6: "Quella che guarda verso terra -Chella ca guarda ‘nterra",
    7: "‘O Vase – Il Vaso",
    8: "A’ Madonna – La Madonna",
    9: "‘A Figliata – La figliolanza",
    10: "‘E Fasule – I fagioli",
    11: "‘E Suricille – I topi",
    12: "‘O Surdate – Il soldato",
    13: "Sant’Antonio",
    14: "‘O ‘Mbriaco – L’ubriaco",
    15: "‘O Guaglione – Il ragazzo",
    16: "‘O Culo – Il culo",
    17: "‘A Disgrazzia – La sfortuna",
    18: "‘O ‘Sanghe – Il sangue",
    19: "‘A Resata – La risata",
    20: "‘A Festa – La festa",
    21: "‘A Femmena annura – La donna nuda",
    22: "‘O Pazzo – Il pazzo",
    23: "‘O Scemo – lo scemo",
    24: "‘E Gguardie – Le guardie",
    25: "Natal’ – Natale",
    26: "Nanninella – Anna",
    27: "‘O Cantero – L’orinale",
    28: "‘E Zzizze – Le tette",
    29: "‘O Pate d”e Ccriature – Il padre dei bimbi",
    30: "‘E Ppalle d”o Tenente – Le palle del Tenente",
    31: "‘O Padrone ‘e Casa – Il padrone dell’abitazione",
    32: "‘O Capitone – Il capitone",
    33: "L’Anne ‘e Cristo – Gli anni di Cristo",
    34: "‘A Capa – La testa",
    35: "L’Aucelluzz – L’uccello",
    36: "‘E Ccastagnelle – Le nacchere",
    37: "‘O Monaco – Il monaco",
    38: "‘E Mmazzate – Le bastonate",
    39: "‘A Funa n’Ganna – La corda al collo",
    40: "‘A Paposcia – L’ernia",
    41: "‘O Curtiello – Il coltello",
    42: "‘O Cafè – Il Caffè",
    43: "Onna pereta fore ‘O barcone – Donna al balcone",
    44: "‘E Ccancelle – Le carceri",
    45: "‘O Vino bbuono – Il buon vino",
    46: "‘E Denare – I soldi",
    47: "‘O Muorto – Il morto",
    48: "‘O Muorto che pparla - Il morto che parla",
    49: "‘O Piezzo ‘e Carne – La carne",
    50: "‘O Ppane – Il pane",
    51: "‘O Ciardino – Il giardino",
    52: "‘A Mamma – La mamma",
    53: "‘O Viecchio – Il vecchio",
    54: "‘O Cappiello – Il cappello",
    55: "‘A Museca – La musica",
    56: "‘A Caruta – La caduta",
    57: "‘O Scartellato – Il gobbo",
    58: "‘O Paccotto – Il cartoccio",
    59: "‘E Pile – I peli",
    60: "Se Lamenta – Si lamenta",
    61: "‘O Cacciatore – Il cacciatore",
    62: "‘O Muorto acciso – Il morto ammazzato",
    63: "‘A Sposa – La sposa",
    64: "‘A Sciammeria – La marsina",
    65: "‘O Chianto – Il pianto",
    66: "‘E ddoie Zetelle – Le due zitelle",
    67: "‘O Totaro int”a Chitarra – Il totano nella chitarra",
    68: "‘A Zuppa cotta – La minestra cotta",
    69: "Sott’e ‘Ncoppa – Sottosopra",
    70: "‘O Palazzo – Il palazzo",
    71: "L’Ommo ‘e Merda – Essere riprovevole",
    72: "A Maraviglia – Lo stupore",
    73: "‘O Spitale – L’ospedale",
    74: "‘A Rotta – La grotta",
    75: "Pullecenella – Pulcinella",
    76: "‘A Funtana – La fontana",
    77: "‘E Riavulille – I diavoli",
    78: "‘A bella Figliola – La prostituta",
    79: "‘O Mariuolo – Il ladro",
    80: "‘A Vocca – La bocca",
    81: "‘E Sciure – I fiori",
    82: "‘A Tavula ‘mbandita – La tavola imbandita",
    83: "‘O Maletiempo – Il maltempo",
    84: "‘A Cchiesa – La chiesa",
    85: "‘Ll Aneme ‘o Priatorio – Le anime del Purgatorio",
    86: "‘A Puteca – Il negozio",
    87: "‘E Perucchie – I pidocchi",
    88: "‘E Casecavalle – I caciocavalli",
    89: "‘A Vecchia – La vecchia",
    90: "‘A Paura – La paura"
};